Add the starman, rrr and watcher init scripts for site.pp

diff --git a/modules/metacpan/templates/init_watcher.erb b/modules/metacpan/templates/init_watcher.erb
--- a/modules/metacpan/templates/init_watcher.erb
+++ b/modules/metacpan/templates/init_watcher.erb
@@ -6,27 +6,27 @@
 # Required-Stop:
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 2 6
-# Short-Description: MetaCPAN API Server
+# Short-Description: <%= desc %>
 ### END INIT INFO
 
 # Check for missing binaries (stale symlinks should not happen)
 # Note: Special treatment of stop for LSB conformance
 source <%= metacpanrc %>
-STARMAN_BIN=<%= perlbin %>/starman
-ROOT=<%= app_root %>
+WATCHER_BIN=<%= app_root %>/bin/metacpan
 PID_FILE=/var/run/<%= filename %>.pid
-test -x $STARMAN_BIN || { echo "$STARMAN_BIN not installed"; 
+ROOT=<%= app_root %>
+test -x $WATCHER_BIN || { echo "$WATCHER_BIN not installed"; 
 	if [ "$1" = "stop" ]; then exit 0;
 	else exit 5; fi; }
 
 # Check for existence of needed config file and read it
-#metacpan-api_CONFIG=/etc/sysconfig/metacpan-api
-#test -r $metacpan-api_CONFIG || { echo "$metacpan-api_CONFIG not existing";
+#metacpan-watcher_CONFIG=/etc/sysconfig/metacpan-watcher
+#test -r $metacpan-watcher_CONFIG || { echo "$metacpan-watcher_CONFIG not existing";
 #	if [ "$1" = "stop" ]; then exit 0;
 #	else exit 6; fi; }
 
 # Read config	
-#. $metacpan-api_CONFIG
+#. $metacpan-watcher_CONFIG
 
 # Source LSB init functions
 # providing start_daemon, killproc, pidofproc, 
@@ -48,7 +48,7 @@ test -x $STARMAN_BIN || { echo "$STARMAN_BIN not installed";
 #      rc_reset         clear both the local and overall rc status
 #      rc_exit          exit appropriate to overall rc status
 #      rc_active        checks whether a service is activated by symlinks
-.    /etc/rc.status
+. /etc/rc.status
 
 # Reset status of this service
 rc_reset
@@ -71,22 +71,20 @@ rc_reset
 
 case "$1" in
     start)
-	echo -n "Starting metacpan-api "
+	echo -n "Starting metacpan-watcher "
 	## Start daemon with startproc(8). If this fails
-	## the return value is set appropriately by startproc.
-	cd $ROOT
-	$STARMAN_BIN --preload-app -D --user metacpan --group users --pid $PID_FILE --error-log <%= error_log %>
+	## the return value is set appropriately by startproc
+	HOME=/home/metacpan /sbin/startproc -e -u metacpan -p $PID_FILE <%= perlbin %>/perl $WATCHER_BIN watcher
 
 	# Remember status and be verbose
 	rc_status -v
 	;;
     stop)
-	echo -n "Shutting down metacpan-api "
+	echo -n "Shutting down metacpan-watcher "
 	## Stop daemon with killproc(8) and if this fails
 	## killproc sets the return value according to LSB.
 
-	/bin/kill `cat $PID_FILE`
-	/bin/rm $PID_FILE
+	/sbin/killproc -p $PID_FILE $WATCHER_BIN 
 
 	# Remember status and be verbose
 	rc_status -v
@@ -117,7 +115,7 @@ case "$1" in
 	rc_status
 	;;
     status)
-	echo -n "Checking for service metacpan-api "
+	echo -n "Checking for service metacpan-watcher "
 	## Check status with checkproc(8), if process is running
 	## checkproc will return with exit status 0.
 
@@ -140,7 +138,7 @@ case "$1" in
 	## argument to this init script which is required for a reload.
 	## Note: probe is not (yet) part of LSB (as of 1.9)
 
-	test /etc/metacpan-api/metacpan-api.conf -nt $PID_FILE && echo reload
+	test /etc/metacpan-watcher/metacpan-watcher.conf -nt $PID_FILE && echo reload
 	;;
     *)
 	echo "Usage: $0 {start|stop|status|try-restart|restart|force-reload|reload|probe}"
